sidekiq:
  extends:
    file: compose_common.yml
    service: sidekiq
  user: 'prod_user'
  volumes:
    - "./log:/opt/app/log"
    - "./config:/opt/app/config"
    - "./production_data/storage:/opt/app/storage"
  env_file:
    - 'production.env'
