db:
  image: "mysql:5.6"
  ports:
    - "3306"

web:
  build: .
  container_name: web
  working_dir: /home/app/webapp
  ports:
    - "8080:80"

sidekiq:
  build: .
  container_name: sidekiq
  working_dir: /home/app/webapp
  command: bundle exec sidekiq

redis:
  image: "redis:2.8"
  ports:
    - "6379:6379"
