web:
  extends:
    file: compose_common.yml
    service: web
  links:
    - redis
  volumes:
      - "./config/sites_enabled:/etc/nginx/sites-enabled/"
      - "./production_data/storage:/home/app/webapp/storage"
  restart: always
  env_file:
    - 'production.env'

redis:
  extends:
    file: compose_common.yml
    service: redis
