version: '2'
services:
  web:
    extends:
      file: compose_common.yml
      service: web
    user: 'dev_user'
    environment:
      - RAILS_ENV=development
    volumes:
      - ".:/opt/app"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  sidekiq:
    extends:
      file: compose_common.yml
      service: sidekiq
    command: bundle exec rerun --background --dir app,db,lib --pattern '{**/*.rb}' -- bundle exec sidekiq --verbose
    user: 'dev_user'
    environment:
      - RAILS_ENV=development
      - OMP_NUM_THREADS=1
    volumes:
      - ".:/opt/app"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  redis:
    extends:
      file: compose_common.yml
      service: redis
    depends_on:
      - db

  db:
    extends:
      file: compose_common.yml
      service: db
