version: '2'
services:
  web:
    build: .
    command: bundle exec unicorn -p 8080 -c config/unicorn.rb
    ports:
      - "3011:8080"
    volumes:
      - "./data/storage:/opt/app/storage"
      - "./data/log:/opt/app/log"
    tmpfs:
      - /tmp
      - /opt/app/tmp:rw,uid=1000,gid=1000

  sidekiq:
    build: .
    hostname: "${HOSTNAME}_worker"
    command: bundle exec sidekiq
    environment:
      - OMP_NUM_THREADS=1
    volumes:
      - "./data/storage:/opt/app/storage"
      - "./data/log:/opt/app/log"
    tmpfs:
      - /tmp:rw,uid=1000,gid=1000
      - /opt/app/tmp:rw,uid=1000,gid=1000

  redis:
    image: "redis:3"
    mem_limit: 512M
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "./config/redis:/usr/local/etc/redis"
    ports:
      - "6379:6379"

  db:
    image: "mysql:5.6"
    mem_limit: 4G
    volumes:
      - "./config/mysql/config:/etc/mysql"
      - "./config/mysql/initialize:/var/tmp/mysql"
      - "./data/database:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
