web:
  extends:
    file: compose_common.yml
    service: web
  environment:
    - PASSENGER_APP_ENV=development
  volumes:
    - ".:/home/app/webapp"
    - "./config/sites_enabled:/etc/nginx/sites-enabled/"
    - "./development_data/storage:/home/app/webapp/storage"
  links:
    - redis
  env_file:
    - development.env

sidekiq:
  extends:
    file: compose_common.yml
    service: sidekiq
  user: app
  environment:
    - PASSENGER_APP_ENV=development
  volumes:
    - ".:/home/app/webapp"
    - "./development_data/storage:/home/app/webapp/storage"
  links:
    - redis
  env_file:
    - development.env

redis:
  extends:
    file: compose_common.yml
    service: redis
