version: '2'
services:
  web:
    container_name: web
    build: .
    # command: bundle exec unicorn -p 8080 -c config/unicorn.rb
    command: foreman start -f Procfile.dev
    ports:
      - "3009:8080"
    volumes:
      - "./data/storage:/opt/app/storage"
      - "./data/log:/opt/app/log"
    tmpfs:
      - /tmp
      - /opt/app/tmp:rw,uid=1000,gid=1000

  sidekiq:
    container_name: sidekiq
    build: .
    hostname: "${HOSTNAME}_worker"
    command: bundle exec sidekiq
    environment:
      - OMP_NUM_THREADS=1
    volumes:
      - "./data/storage:/opt/app/storage"
      - "./data/log:/opt/app/log"
    tmpfs:
      - /tmp:rw,uid=1000,gid=1000
      - /opt/app/tmp:rw,uid=1000,gid=1000

  redis:
    container_name: redis
    image: "redis:3"
    command: redis-server --save 900 1
    ports:
      - "6379:6379"

  db:
    container_name: db
    image: "mysql:5.7"
    mem_limit: 4G
    volumes:
      - "./config/mysql:/etc/mysql/conf.d"
      - "./data/database:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306"
