web:
  extends:
    file: compose_common.yml
    service: web
  links:
    - redis
  volumes:
      - ".:/opt/app"
      - "./production_data/storage:/opt/app/storage"
  restart: always
  env_file:
    - 'production.env'

redis:
  extends:
    file: compose_common.yml
    service: redis
