version: '2'
services:
  web:
    extends:
      file: compose_common.yml
      service: web
    user: 'dev_user'
    volumes:
      - ".:/opt/app"
    links:
      - db
      - redis

  sidekiq:
    extends:
      file: compose_common.yml
      service: sidekiq
    user: 'dev_user'
    volumes:
      - ".:/opt/app"
    links:
      - db
      - redis

  redis:
    extends:
      file: compose_common.yml
      service: redis

  db:
    extends:
      file: compose_common.yml
      service: db
