version: '2'
services:
  web:
    extends:
      file: compose_common.yml
      service: web
    user: 'prod_user'
    volumes:
      - "./data/log:/opt/app/log"
      - "./data/storage:/opt/app/storage"
    restart: always
    env_file:
      - 'production.env'
