web:
  extends:
    file: compose_common.yml
    service: web
  user: 'prod_user'
  links:
    - redis
  volumes:
    - "./log:/opt/app/log"
    - "./production_data/storage:/opt/app/storage"
  restart: always
  env_file:
    - 'production.env'

redis:
  extends:
    file: compose_common.yml
    service: redis
