web:
  extends:
    file: compose_common.yml
    service: web
  user: 'dev_user'
  volumes:
    - ".:/opt/app"
    - "./development_data/storage:/opt/app/storage"
  links:
    - redis
  env_file:
    - development.env

sidekiq:
  extends:
    file: compose_common.yml
    service: sidekiq
  user: 'dev_user'
  volumes:
    - ".:/opt/app"
    - "./development_data/storage:/opt/app/storage"
  links:
    - redis
  env_file:
    - development.env

redis:
  extends:
    file: compose_common.yml
    service: redis

guard:
  extends:
    file: compose_common.yml
    service: web
  privileged: true
  user: 'root'
  command: bash -c "sysctl -w fs.inotify.max_user_watches=524288 && bundle exec guard"
  volumes:
    - ".:/opt/app"
    - "./development_data/storage:/opt/app/storage"
  env_file:
    - development.env
