db:
  image: "mysql:5.6"
  ports:
    - "3306"

web:
  build: .
  command: bundle exec unicorn -p 8080 -c config/unicorn.rb
  ports:
    - "3009:8080"

sidekiq:
  build: .
  command: bundle exec sidekiq

redis:
  image: "redis:2.8"
  ports:
    - "6379:6379"
