sidekiq:
  extends:
    file: compose_common.yml
    service: sidekiq
  image: 'anzaika/selectoscope'
  user: 'prod_user'
  volumes:
    - "./log:/opt/app/log"
    - "./production_data/storage:/opt/app/storage"
  env_file:
    - 'production.env'
  command: "bundle exec sidekiq -P tmp/sidekiq.pid -c 32 -L ./log/sidekiq_many_on_${HOSTNAME}.log"
