sidekiq:
  extends:
    file: compose_common.yml
    service: sidekiq
  image: 'anzaika/selectoscope'
  user: 'prod_user'
  volumes:
    - "./log:/opt/app/log"
    - "./production_data/storage:/opt/app/storage"
  environment:
    - OPENMP_NUM_THREADS=4
  env_file:
    - 'production.env'
  command: "bundle exec sidekiq -P tmp/sidekiq.pid -q four -c 4 -L ./log/sidekiq_four_on_${HOSTNAME}.log"
