version: "2"
services:
  guard:
    build: .
    depends_on:
      - test_db
    container_name: guard
    working_dir: /opt/app
    privileged: true
    user: 'root'
    environment:
      - RAILS_ENV=test
    volumes:
      - ".:/opt/app"
      - "/home/anzaika/fast/selectoscope_test_storage:/opt/app/storage"
    tmpfs:
      - /tmp:rw,uid=1000,gid=1000
      - /opt/app/tmp:rw,uid=1000,gid=1000
    links:
      - test_db

  test_db:
    image: "mysql:5.7"
    volumes:
      - "/home/anzaika/fast/selectoscope_test_database:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306"
