web:
  extends:
    file: common.yml
    service: web
  user: 'dev_user'
  volumes:
    - ".:/opt/app"
  links:
    - redis
  env_file:
    - 'development.env'

sidekiq:
  extends:
    file: common.yml
    service: sidekiq
  user: 'dev_user'
  volumes:
    - ".:/opt/app"
  links:
    - redis
  env_file:
    - 'development.env'

redis:
  extends:
    file: common.yml
    service: redis
