# db:
#   extends:
#     file: common.yml
#     service: db
#   volumes:
#     - "./production_data/database:/var/lib/mysql"
#   restart: always
#   env_file:
#     - 'production.env'
#
web:
  extends:
    file: common.yml
    service: web
  links:
    # - db
    - redis
  volumes:
      - "./production_data/fasta_files:/opt/app/public/fasta_file"
      - "./production_data/log:/opt/app/log"
      - "./production_data/tmp:/opt/app/tmp"
  restart: always
  env_file:
    - 'production.env'

# sidekiq:
#   extends:
#     file: common.yml
#     service: sidekiq
#   volumes:
#     - "./rails:/opt/app"
#     - "./production_data/fasta_files:/opt/app/public/fasta_file"
#     - "./production_data/tmp:/opt/app/tmp"
#     - "./production_data/log:/opt/app/log"
#   links:
#     - db
#     - redis
#   env_file:
#     - 'production.env'

redis:
  extends:
    file: common.yml
    service: redis
