common: &common
  adapter: mysql2
  host: db
  reconnect: true
  encoding: utf8
  port: 3306
  pool: 12
  username: root
  password: 1234

production:
  <<: *common
  pool: <%= ENV["DB_POOL"] %>
  host: <%= ENV["DB_HOST"] %>
  pool: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_DATABASE"] %>

development:
  <<: *common
  database: db

test:
  <<: *common
  database: db_test
