---
:pidfile: tmp/sidekiq.pid
development:
  :concurrency: 4
  :queues:
    - many
    - control
  :process_limits:
    many: 2
    control: 2
production:
  :logfile: ./log/sidekiq.log
  :concurrency: 32
  :queues:
    - many
    - control
  :process_limits:
    many: 16
    control: 16
