---
:pidfile: tmp/sidekiq.pid
development:
  :concurrency: 1
  :queues:
    - one
    - parallel_four
    - many
  :limits:
    one: 1
    parallel_four: 1
    many: 4
production:
  :logfile: ./log/sidekiq.log
  :concurrency: 16
  :queues:
    - one
    - parallel_four
    - many
  :limits:
    one: 1
    parallel_four: 4
    many: 16
:blocking:
  - one
