---
:pidfile: tmp/sidekiq.pid
development:
  :concurrency: 10
  :queues:
    - four
    - many
    - control
  :limits:
    four: 1
    many: 4
production:
  :logfile: ./log/sidekiq.log
  :concurrency: 32
  :queues:
    - four
    - many
    - control
  :limits:
    four: 4
    many: 16
:blocking:
  - one
