---
:pidfile: tmp/sidekiq.pid
development:
  :concurrency: 10
  :queues:
    - many
    - control
  :process_limits:
    many: 4
    control: 4
production:
  :logfile: ./log/sidekiq.log
  :concurrency: 30
  :queues:
    - many
    - control
  :process_limits:
    many: 15
    control: 15
