---
:pidfile: tmp/sidekiq.pid
development:
  :logfile: <%= "./log/sidekiq_on_#{`hostname`.strip}.log" %>
  :concurrency: 8
  :queues:
    - many
    - four
    - control
  :process_limits:
    many: 2
    control: 2
production:
  :logfile: <%= "./log/sidekiq_on_#{`hostname`.strip}.log" %>
  :concurrency: 32
  :queues:
    - many
    - control
  :process_limits:
    many: 16
    control: 16
