web:
  extends:
    file: common.yml
    service: web
  volumes:
    - ".:/opt/app"
    - "./development_data/fasta_files:/opt/app/public/fasta_file"
    - "./development_data/log:/opt/app/log"
    - "./development_data/tmp:/opt/app/tmp"
  links:
    - redis
  env_file:
    - 'development.env'

sidekiq:
  extends:
    file: common.yml
    service: sidekiq
  volumes:
    - ".:/opt/app"
    - "./development_data/fasta_files:/opt/app/public/fasta_file"
    - "./development_data/tmp:/opt/app/tmp"
    - "./development_data/log:/opt/app/log"
  links:
    - redis
  env_file:
    - 'development.env'

redis:
  extends:
    file: common.yml
    service: redis
